export default {
  Events: {
    CRON_CREATED: 'cron:created',
    CRON_REMOVED: 'cron:removed',
    CRON_STARTED: 'cron:started',
    CRON_STOPPED: 'cron:stopped',
    CRON_RUNNING: 'cron:running',
    CRON_FINISHED: 'cron:finished',
    MEETING_CREATED: 'meeting:created',
    MEETING_MODIFIED: 'meeting:modified',
    MEETING_REMOVED: 'meeting:removed',
    MEETING_STARTED: 'meeting:started',
    MEETING_FINISHED: 'meeting:finished',
    SERVER_SETTING_UPDATED: 'server-setting:updated',
  },
  Modules: {
    //CRON_JFT: 'cron:jft',
    //CRON_FETCH_MEETINGS: 'cron:fetch-meetings',
    //CRON_MEETING_REMINDER: 'cron:meeting-reminder',
    CRON_NEW_MEMBER: 'cron:test',
    CRON_VOICE_OF_SEREN: 'cron:voiceofseren',
    CRON_WARBANDS: 'cron:warbands',
    CRON_SINKHOLE: 'cron:sinkhole'
  },
  Meetings: {
    Sources: {
      VIRTUAL_NA: 1,
    },
    NaOnlineSources: {
      AUSTRALIA: {
        name: 'Australia',
        sources: [1, 13],
        timezone: 'Australia/Sydney',
      },
      ITALY: {
        name: 'Italy',
        sources: [5],
        timezone: 'Europe/Rome',
      },
      FARSI: {
        name: 'Farsi',
        sources: [12, -12],
        timezone: 'Asia/Tehran',
      },
      DORSET_AREA: {
        name: 'Dorset Area',
        sources: [17],
        timezone: 'Europe/Belfast',
      },
      PHONE: {
        name: 'Phone',
        sources: [3],
        timezone: 'GMT',
      },
      INDIA: {
        name: 'India',
        sources: [11],
        timezone: 'Asia/Kolkata',
      },
      PORTUGESE: {
        name: 'Portugese',
        sources: [7, 9],
        timezone: 'Europe/Lisbon',
      },
      BRAZIL: {
        name: 'Brazil',
        sources: [9],
        timezone: 'America/Sao_Paulo',
      },
      SOUTH_AMERICA: {
        name: 'South America',
        sources: [6],
        timezone: 'America/Sao_Paulo',
      },
      US: {
        name: 'USA',
        sources: [15],
        timezone: 'America/New_York',
      },
      RUSSIA: {
        name: 'Russia',
        sources: [8],
        timezone: 'Europe/Moscow',
      },
      FRANCE: {
        name: 'France',
        sources: [-10],
        timezone: 'Europe/Paris',
      },
    }
  },
  Colors: {
    DEFAULT: "#BBCCBB",
    ALICEBLUE: "#F0F8FF",
    ANTIQUEWHITE: "#FAEBD7",
    AQUA: "#00FFFF",
    AQUAMARINE: "#7FFFD4",
    AZURE: "#F0FFFF",
    BEIGE: "#F5F5DC",
    BISQUE: "#FFE4C4",
    BLACK: "#000000",
    BLANCHEDALMOND: "#FFEBCD",
    BLUE: "#0000FF",
    BLUEVIOLET: "#8A2BE2",
    BROWN: "#A52A2A",
    BURLYWOOD: "#DEB887",
    CADETBLUE: "#5F9EA0",
    CHARTREUSE: "#7FFF00",
    CHOCOLATE: "#D2691E",
    CORAL: "#FF7F50",
    CORNFLOWERBLUE: "#6495ED",
    CORNSILK: "#FFF8DC",
    CRIMSON: "#DC143C",
    CYAN: "#00FFFF",
    DARKBLUE: "#00008B",
    DARKCYAN: "#008B8B",
    DARKGOLDENROD: "#B8860B",
    DARKGRAY: "#A9A9A9",
    DARKGREEN: "#006400",
    DARKGREY: "#A9A9A9",
    DARKKHAKI: "#BDB76B",
    DARKMAGENTA: "#8B008B",
    DARKOLIVEGREEN: "#556B2F",
    DARKORANGE: "#FF8C00",
    DARKORCHID: "#9932CC",
    DARKRED: "#8B0000",
    DARKSALMON: "#E9967A",
    DARKSEAGREEN: "#8FBC8F",
    DARKSLATEBLUE: "#483D8B",
    DARKSLATEGRAY: "#2F4F4F",
    DARKSLATEGREY: "#2F4F4F",
    DARKTURQUOISE: "#00CED1",
    DARKVIOLET: "#9400D3",
    DEEPPINK: "#FF1493",
    DEEPSKYBLUE: "#00BFFF",
    DEFAULTCOLOR: "#BBCCBB",
    DIMGRAY: "#696969",
    DIMGREY: "#696969",
    DODGERBLUE: "#1E90FF",
    FIREBRICK: "#B22222",
    FLORALWHITE: "#FFFAF0",
    FORESTGREEN: "#228B22",
    FUCHSIA: "#FF00FF",
    GAINSBORO: "#DCDCDC",
    GHOSTWHITE: "#F8F8FF",
    GOLD: "#FFD700",
    GOLDENROD: "#DAA520",
    GRAY: "#808080",
    GREEN: "#008000",
    GREENYELLOW: "#ADFF2F",
    GREY: "#808080",
    HONEYDEW: "#F0FFF0",
    HOTPINK: "#FF69B4",
    INDIANRED: "#CD5C5C",
    INDIGO: "#4B0082",
    IVORY: "#FFFFF0",
    KHAKI: "#F0E68C",
    LAVENDER: "#E6E6FA",
    LAVENDERBLUSH: "#FFF0F5",
    LAWNGREEN: "#7CFC00",
    LEMONCHIFFON: "#FFFACD",
    LIGHTBLUE: "#ADD8E6",
    LIGHTCORAL: "#F08080",
    LIGHTCYAN: "#E0FFFF",
    LIGHTGOLDENRODYELLOW: "#FAFAD2",
    LIGHTGRAY: "#D3D3D3",
    LIGHTGREEN: "#90EE90",
    LIGHTGREY: "#D3D3D3",
    LIGHTPINK: "#FFB6C1",
    LIGHTSALMON: "#FFA07A",
    LIGHTSEAGREEN: "#20B2AA",
    LIGHTSKYBLUE: "#87CEFA",
    LIGHTSLATEGRAY: "#778899",
    LIGHTSLATEGREY: "#778899",
    LIGHTSTEELBLUE: "#B0C4DE",
    LIGHTYELLOW: "#FFFFE0",
    LIME: "#00FF00",
    LIMEGREEN: "#32CD32",
    LINEN: "#FAF0E6",
    MAGENTA: "#FF00FF",
    MAROON: "#800000",
    MEDIUMAQUAMARINE: "#66CDAA",
    MEDIUMBLUE: "#0000CD",
    MEDIUMORCHID: "#BA55D3",
    MEDIUMPURPLE: "#9370DB",
    MEDIUMSEAGREEN: "#3CB371",
    MEDIUMSLATEBLUE: "#7B68EE",
    MEDIUMSPRINGGREEN: "#00FA9A",
    MEDIUMTURQUOISE: "#48D1CC",
    MEDIUMVIOLETRED: "#C71585",
    MIDNIGHTBLUE: "#191970",
    MINTCREAM: "#F5FFFA",
    MISTYROSE: "#FFE4E1",
    MOCCASIN: "#FFE4B5",
    NAVAJOWHITE: "#FFDEAD",
    NAVY: "#000080",
    OLDLACE: "#FDF5E6",
    OLIVE: "#808000",
    OLIVEDRAB: "#6B8E23",
    ORANGE: "#FFA500",
    ORANGERED: "#FF4500",
    ORCHID: "#DA70D6",
    PALEGOLDENROD: "#EEE8AA",
    PALEGREEN: "#98FB98",
    PALETURQUOISE: "#AFEEEE",
    PALEVIOLETRED: "#DB7093",
    PAPAYAWHIP: "#FFEFD5",
    PEACHPUFF: "#FFDAB9",
    PERU: "#CD853F",
    PINK: "#FFC0CB",
    PLUM: "#DDA0DD",
    POWDERBLUE: "#B0E0E6",
    PURPLE: "#800080",
    REBECCAPURPLE: "#663399",
    RED: "#FF0000",
    ROSYBROWN: "#BC8F8F",
    ROYALBLUE: "#4169E1",
    SADDLEBROWN: "#8B4513",
    SALMON: "#FA8072",
    SANDYBROWN: "#F4A460",
    SEAGREEN: "#2E8B57",
    SEASHELL: "#FFF5EE",
    SIENNA: "#A0522D",
    SILVER: "#C0C0C0",
    SKYBLUE: "#87CEEB",
    SLATEBLUE: "#6A5ACD",
    SLATEGRAY: "#708090",
    SLATEGREY: "#708090",
    SNOW: "#FFFAFA",
    SPRINGGREEN: "#00FF7F",
    STEELBLUE: "#4682B4",
    TAN: "#D2B48C",
    TEAL: "#008080",
    THISTLE: "#D8BFD8",
    TOMATO: "#FF6347",
    TURQUOISE: "#40E0D0",
    VIOLET: "#EE82EE",
    WHEAT: "#F5DEB3",
    WHITE: "#FFFFFF",
    WHITESMOKE: "#F5F5F5",
    YELLOW: "#FFFF00",
    YELLOWGREEN: "#9ACD32"
  },
  // Colors: {
  //   DEFAULT: 0,
  //   AQUA: 1752220,
  //   GREEN: 3066993,
  //   BLUE: 3447003,
  //   PURPLE: 10181046,
  //   GOLD: 15844367,
  //   ORANGE: 15105570,
  //   RED: 15158332,
  //   GREY: 9807270,
  //   DARKER_GREY: 8359053,
  //   NAVY: 3426654,
  //   DARK_AQUA: 1146986,
  //   DARK_GREEN: 2067276,
  //   DARK_BLUE: 2123412,
  //   DARK_PURPLE: 7419530,
  //   DARK_GOLD: 12745742,
  //   DARK_ORANGE: 11027200,
  //   DARK_RED: 10038562,
  //   DARK_GREY: 9936031,
  //   LIGHT_GREY: 12370112,
  //   DARK_NAVY: 2899536,
  //   LUMINOUS_VIVID_PINK: 16580705,
  //   DARK_VIVID_PINK: 12320855,
  // },
};
